apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: container-demo-app
  name: container-demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: container-demo-app
  template:
    metadata:
      labels:
        app: container-demo-app
    spec:
      containers:
      - name: container-demo-app
        image: docker.io/tobimason/container-demo-app:1.2
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: container-demo-app
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
