apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: container-demo-app
  name: container-demo-app
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: container-demo-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: container-demo-app
    spec:
      containers:
      - name: container-demo-app
        image: docker.io/tobimason/container-demo-app:1.1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: container-demo-app
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
